name: 'Container image scan'
description: 'Scan container images for vulnerabilities and CIS guidelines'
inputs: 
  image-name:
    description: 'Docker image to scan'
    required: true
  whitelist-file:
    description: 'Path to the whitelist file'
    required: false
  whitelist-file-branch:
    description: 'Branch from which whitelist file is to be downloaded'
    default: 'master'
    required: false
  severity-threshold:
    description: 'severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    reuired: false
  username:
    description: 'Username to authenticate to the Docker registry'
    required: false
  password:
    description: 'Password to authenticate to the Docker registry'
    required: false
  github-token:
    description: 'Github token to download whitelist file'
    default: ${{ github.token }}
  add-CIS-checks:
    description: 'Add CIS checks to build secure and best pracitce Docker images'
    default: 'true'
  registry-url:
    description: 'Rgistry URL'
    default: 'https://registry.hub.docker.com'

outputs:
  scan-report:
    description: 'File name where the scan results are stored'

runs:
  using: 'node12'
  main: 'lib/main.js'