name: 'Container image scan'
description: 'Scan container images for vulnerabilities and CIS guidelines'
inputs: 
  image-name:
    description: 'Docker image to scan'
    required: true
  severity-threshold:
    description: 'severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
  username:
    description: 'Username to authenticate to the Docker registry'
    required: false
  password:
    description: 'Password to authenticate to the Docker registry'
    required: false
  add-CIS-checks:
    description: 'Add CIS checks to build secure and best pracitce Docker images'
    default: 'true'
  github-token:
    description: 'Github token'
    default: ${{ github.token }}

outputs:
  scan-report:
    description: 'File name where the scan results are stored'

runs:
  using: 'node12'
  main: 'lib/main.js'